/**
 * Guide Builder（指导书 Spec 3.3 / 6.3 / 13.1）：
 * 从 ControlProfile 档案源（唯一结构化来源）生成：
 *   1. docs/motion-guides/<modelId>.md   —— 角色说明书（十个固定章节，人/LLM 可读）
 *   2. docs/motion-guides/common.md      —— 共享基础规范（协议/单位/预算；由本脚本内常量+schema 派生）
 * 生成文件头部带 GENERATED 标记：人工编辑不改变程序边界（Spec 6.3），修改须回到源定义重建。
 *
 * 用法: npx vite-node scripts/build-guides.mts [characters/<model>.rig-profile.json ...]
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parseControlProfile, openControls, type ControlProfile, type ControlDefinition } from "../src/rig/controlProfile.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const outDir = resolve(root, "docs/motion-guides");
mkdirSync(outDir, { recursive: true });

const BANNER = (source: string) =>
  `<!-- GENERATED by scripts/build-guides.mts · 来源：${source} · 人工编辑不改变程序边界，修改请回源定义并重建（Spec 6.3） -->\n\n`;

// ---------------------------------------------------------------------------
// common.md：共享基础规范（每次请求必带的精简版的母本）
// ---------------------------------------------------------------------------

const COMMON_TEXT = `# 共享基础规范（共享指导规范 · 按预算装配的母本）

## 输出协议
- 只输出一个 JSON 对象：\`{ "status": "motion" | "unsupported" | "needs_context", ... }\`（严格判别联合，未知字段拒绝）。
- \`status="motion"\`：附 \`draft\`（有限时长关键帧草稿）。\`unsupported\`：附 \`reasonCode\`+\`details\`，不含曲线。\`needs_context\`：附 \`requestedCapabilities\`+\`details\`，不猜参数。
- \`requestId / contextId / profileDigest\` 原样回传，不得改写。
- 禁止输出脚本、表达式、注释或 JSON 之外的任何文本。

## 草稿格式（schemaVersion = pliette.motion-draft/1.1）
- \`durationSec\`：有限正数，默认预算 0.4～2.0 秒。
- \`phases\`（可选）：\`prepare / stroke / hold / recover\`，覆盖 [0, durationSec]、有序不重叠。
- \`curves\`：至少 1 条、最多按请求预算（默认每片段 ≤6 个控制器、每曲线 2～6 关键帧、总计 ≤24 关键帧）。
- 每条曲线只引用一个请求开放列表中的 \`controlId\`；同一 controlId 不重复；省略的控制器=不申请写入（不会归零）。
- \`keys\`：\`{ timeSec, value, ease }\`；首键 timeSec=0，末键=durationSec，严格递增；ease 作用于本键到下一键，末键不带 ease。
- \`ease\`：连续参数只允许 \`linear / smooth\`（smooth 为程序固定的有界缓动）；在线禁用 stepped；附件曲线只允许 stepped。
- 数值必须有限（禁止 NaN/Infinity）；数值类型由控制器决定（标量/二元向量/枚举字符串）。

## 单位与参考
- 旋转：度，相对档案参考姿态的偏移；符号按各控制器标注（左右不对称，禁止镜像推算）。
- 位移：身高 H 的比例，父骨局部空间；程序负责一切坐标转换。
- 归零=回到该控制器参考目标；入场从当前姿态混入、退出交还基础动画，均由程序处理。

## 硬边界（违反即拒绝）
- 只能引用请求 \`availableControls\` 中的控制器；写陌生控制名不会获得访问权。
- 数值域分两层：\`allowed\` 之外直接拒绝；\`verified\` 之外执行但记为失败并保留原值。
- 速率上限（度/秒或 H/秒）来自标定，超限拒绝。
- 不支持的能力返回 \`unsupported\`；缺上下文返回 \`needs_context\`，不要伪造。
`;

function writeCommon(): void {
  const text = BANNER("scripts/build-guides.mts（COMMON_TEXT 常量；协议字段与 schemas/motion-draft.v11.schema.json 一致）") + COMMON_TEXT;
  writeFileSync(resolve(outDir, "common.md"), text);
  console.log("生成 docs/motion-guides/common.md");
}

// ---------------------------------------------------------------------------
// <modelId>.md：角色说明书（Spec 3.3 十个固定章节）
// ---------------------------------------------------------------------------

function fmtVal(v: number | [number, number] | string | undefined): string {
  if (v == null) return "—";
  return Array.isArray(v) ? `[${v.join(", ")}]` : String(v);
}

function controlRow(c: ControlDefinition): string {
  const d = c.domain;
  const verified = d.verifiedMin != null || d.verifiedMax != null ? `${fmtVal(d.verifiedMin)} ~ ${fmtVal(d.verifiedMax)}` : "未标定";
  const allowed = d.min != null || d.max != null ? `${fmtVal(d.min)} ~ ${fmtVal(d.max)}` : "—";
  const rate = c.rate?.maxPerSec != null ? `${c.rate.maxPerSec}/s` : "—";
  const input = c.input.type === "enum" ? `enum(${(c.input.enumValues ?? []).join("/")})` : c.input.type;
  return `| \`${c.controlId}\` | ${c.semanticPart} | ${input} ${c.input.unit} | ${fmtVal(c.input.refValue)} | ${allowed} | ${verified} | ${rate} | ${c.status} |`;
}

function buildGuide(profile: ControlProfile, sourcePath: string): string {
  const id = profile.identity;
  const open = openControls(profile);
  const coveragePath = resolve(root, `experiments/rig-calibration/${id.modelId}/write-coverage.json`);
  const coverage = existsSync(coveragePath) ? JSON.parse(readFileSync(coveragePath, "utf-8")) : null;

  const L: string[] = [];
  L.push(`# ${id.modelId} 动作说明书（profileRevision ${id.profileRevision}）`);
  L.push("");
  L.push(`- profileId：\`${id.profileId}\` · **profileDigest：\`${profile.profileDigest}\`**（候选绑定与缓存键）`);
  L.push(`- 资产摘要：\`${id.assetDigest}\` · 导出 ${id.runtimeRef.exportVersion} · 运行时 ${id.runtimeRef.runtimeVersion}（${id.runtimeRef.runtimeSource}）`);
  L.push(`- 视图：${id.viewId} · Skin：${id.skinId}${id.orientationVariant ? ` · 朝向：${id.orientationVariant}` : ""}`);
  L.push(`- 开放控制器：${open.length}/${profile.controls.length}（其余为 candidate/unknown，不在请求开放列表中）`);
  L.push("");

  // 1 身体结构摘要
  L.push("## 1. 身体结构摘要");
  L.push("");
  L.push("二次元 Q 版立绘角色：头身比约 1:1（大头短肢），正面站姿，全身。素材为单张图集的纸片拼装（网格变形有限）。");
  L.push(`- 静态清单：${coverage ? `${(coverage.animations ?? []).length} 段原动画` : "动画清单见资产报告"}；骨骼/Slot 总数见证据表。`);
  L.push("- 视图：仅正面（无背面素材；镜像不等于背面）。半身/转身类请求应返回 unsupported。");
  L.push("- 原动画是动作质量的基准：生成曲线只做短 gesturo 叠加，不替代原动画。");
  L.push("");

  // 2 骨架拓扑与关键关系
  L.push("## 2. 骨架拓扑与关键关系");
  L.push("");
  L.push("与控制相关的真实层级（完整索引见 write-coverage / reference-pose 记录）：");
  L.push("");
  L.push("```");
  L.push("root");
  L.push("├─ leg_L（IK 目标）   leg_R（IK 目标）          ← 脚部世界锚点，不随躯干动");
  L.push("└─ bone");
  L.push("   ├─ body（躯干，setup rot=-90°）              ← 手臂链与腿链的父级");
  L.push("   │   ├─ hand_L（屏幕左臂） → hand_L3");
  L.push("   │   ├─ hand_R（屏幕右臂） → hand_R3");
  L.push("   │   └─ leg_L1 → leg_L3 ；leg_R1 → leg_R3    ← 两条腿 IK：mix=1 常开");
  L.push("   └─ face（头，setup rot=+90°）                ← body 的兄弟节点！");
  L.push("```");
  L.push("");
  L.push("**关键关系（实测）**：头与躯干是兄弟——躯干倾斜/位移**不带动头部**；躯干旋转/平移时双腿 IK 保持脚在原地（腿部再弯折）；手臂链无 IK，FK 直接生效。");
  L.push("");

  // 3 控制器字典
  L.push("## 3. 控制器字典（开放集合）");
  L.push("");
  L.push("| controlId | 部位 | 输入 | 参考 | allowed | verified | 速率上限 | 状态 |");
  L.push("| --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const c of open) L.push(controlRow(c));
  L.push("");
  for (const c of open) {
    L.push(`### \`${c.controlId}\``);
    L.push("");
    L.push(`- **正方向**：${c.input.positiveLooksLike}`);
    L.push(`- **负方向**：${c.input.negativeLooksLike}`);
    L.push(`- **行为**：${c.behavior}`);
    L.push(`- **写入**：${c.ownership.writes.join("、") || "（由子控制器写入）"}`);
    if (c.ownership.dependsOn.length) L.push(`- **依赖/间接影响**：${c.ownership.dependsOn.join("；")}`);
    if (c.binding.compositeEntries?.length) {
      L.push(`- **枚举映射**：${c.binding.compositeEntries.map((e) => `\`${e.key}\``).join("、")}`);
    }
    if (c.conditions?.length) L.push(`- **条件**：${c.conditions.join("；")}`);
    L.push("");
  }

  // 4 参考姿态与坐标
  L.push("## 4. 参考姿态与坐标");
  L.push("");
  L.push(`- 参考姿态：\`${id.referencePose.poseId}\`（digest \`${id.referencePose.digest}\`）——${id.referencePose.description}`);
  L.push(`- 角度：${id.coordinateConvention.angle}`);
  L.push(`- 位移：${id.coordinateConvention.translation}`);
  L.push(`- 左右：${id.coordinateConvention.leftRight}`);
  L.push(`- 身高：H = ${id.heightUnits} 原生单位（标定值，不随逐帧包围盒变化）`);
  L.push("");

  // 5 作用链
  L.push("## 5. 作用链");
  L.push("");
  L.push(`写集覆盖实测（${coverage ? "write-coverage.json" : "待生成"}）：**全部 ${coverage?.animations?.length ?? 20} 段原动画都写入全部关键骨与双眼附件**——基础层完全覆盖。因此：`);
  L.push("");
  L.push("1. 生成曲线在高层轨道以满权重**绝对接管**所写属性（非叠加混合）；");
  L.push("2. 混入期从当前合成姿态平滑过渡，混出后属性交还基础动画；");
  L.push("3. 不存在\"无主骨骼\"——省略的控制器保持基础动画原样，不必（也不应）写 0。");
  L.push("");

  // 6 已标定范围和条件
  L.push("## 6. 已标定范围和条件");
  L.push("");
  L.push("见第 3 章字典（allowed=程序硬边界；verified=标定复核范围，超出执行但计失败）。全部探针在隔离实例 + setup 参考姿态 + front 视图下完成；基础动画相位上的组合验证见第 7 章。");
  L.push("");

  // 7 组合与接触规则
  L.push("## 7. 组合与接触规则");
  L.push("");
  L.push("- 双臂可并行（写集隔离，共享 body 祖先）；同通道两控制器互斥调度。");
  L.push("- 头+躯干倾斜需显式组合（兄弟拓扑，无自动联动）。");
  L.push("- 眼睛只能经 `face.eyes.pair` 成对切换（单眼写入被 requiresCapability 规则拒绝）。");
  L.push(`- 规则清单：${profile.rules.map((r) => `\`${r.ruleId}\`(${r.type})`).join("、")}`);
  L.push("- **接触类能力未实现**：托腮/持物/牵手等接触依赖没有已验证控制器——相关请求返回 unsupported，不得生成近似曲线冒充。");
  L.push("");

  // 8 设计案例与反例
  L.push("## 8. 设计案例与反例");
  L.push("");
  for (const e of profile.evidence) {
    if (e.observation.includes("反例") || e.input.includes("反例")) {
      L.push(`**反例（${e.evidenceId}）**：${e.input}。结果：${e.samples ?? ""}${e.observation ? " " + e.observation : ""}`);
      L.push("");
    }
  }
  L.push("**案例索引**：");
  L.push("");
  L.push("- 呼吸待机：torso.bob y 0→0.008H→0（1.2s，smooth）——P1 已验证节奏。");
  L.push("- 眨眼：face.eyes.pair `blink` 0.1~0.15s 短窗（stepped）。");
  L.push("- 挥手：arm.right.raise 0→+45→+50→+45 两来回→0（原动画 stand[4.9-7.3] 是美术母本）。");
  L.push("");

  // 9 能力缺口和替代策略
  L.push("## 9. 能力缺口和替代策略");
  L.push("");
  L.push("| 缺口 | 事实 | 在线策略 |");
  L.push("| --- | --- | --- |");
  L.push("| 嘴部/口型 | 无独立 mouth Slot/附件 | 口型类请求 → unsupported；表情用眼睛配对表达 |");
  L.push("| 背面/转身 | 无背面附件（67 附件核查） | → unsupported（requiresVariant 规则强制 front） |");
  L.push("| 独立手指 | 无手指骨骼 | 手部细节不可控，用整臂+前臂表达 |");
  L.push("| 行走 | walk 为原动画切片能力 | 行走由切片库/调度器提供，不生成腿部曲线 |");
  L.push("| 接触（托腮等） | 无已验证接触控制器 | → unsupported；不得现场生成求解器 |");
  L.push("");

  // 10 证据与版本
  L.push("## 10. 证据与版本");
  L.push("");
  L.push("| evidenceId | 类型 | 输入 | 结论摘要 | 状态 | 日期 |");
  L.push("| --- | --- | --- | --- | --- | --- |");
  for (const e of profile.evidence) {
    const brief = (e.observation ?? "").slice(0, 60);
    L.push(`| \`${e.evidenceId}\` | ${e.kind} | ${e.input.slice(0, 50)}${e.input.length > 50 ? "…" : ""} | ${brief}${(e.observation ?? "").length > 60 ? "…" : ""} | ${e.status} | ${e.date} |`);
  }
  L.push("");
  L.push(`> 状态语义：\`verified\` 仅表示在记录条件（视图/Skin/参考姿态/基础动画）下通过当前验收，不是对任意组合的保证。修订链：profileRevision ${id.profileRevision}；改动资产/Skin/参考姿态/控制映射/规则任一项，旧验证范围不自动继承（Spec 3.1）。`);
  L.push("");
  return BANNER(`${sourcePath}（经 parseControlProfile 校验）`) + L.join("\n");
}

// ---------------------------------------------------------------------------
// 执行
// ---------------------------------------------------------------------------

const inputs = process.argv.slice(2);
if (inputs.length === 0) {
  console.error("用法: npx vite-node scripts/build-guides.mts characters/lafei_8.rig-profile.json [...]");
  process.exit(1);
}
writeCommon();
for (const input of inputs) {
  const src = resolve(root, input);
  const profile = parseControlProfile(JSON.parse(readFileSync(src, "utf-8")));
  const modelId = profile.identity.modelId;
  const outFile = resolve(outDir, `${modelId}.md`);
  writeFileSync(outFile, buildGuide(profile, relative(root, src)));
  console.log(`生成 docs/motion-guides/${modelId}.md（digest ${profile.profileDigest}，开放 ${openControls(profile).length} 控制）`);
}
console.log("完成 ->", relative(root, outDir));
